reuse-data1/djangoproject/urls.py
## This can be deleted later (this admin import)
from django.contrib import admin

from django.urls import path, include
from django.views.generic import TemplateView

from login.views import logout
from pricing.views import template_home



urlpatterns = [
    path('admin/', admin.site.urls), ## can be deleted later
    path('mm/',include('mm.urls')),
    path('idh/',include('idh.urls')),
    path('reports/',include('reports.urls')),
    path('shopify/', include('shopify.urls')),
    path('visitors/',include('visitors.urls')),
    path('pricing/', include('pricing.urls')),
    path('giftcardportal/', include('qbgiftcard.urls')),

    path('accounts/', include('allauth.urls')),

    path('', template_home, name='HOME'),
    # ORIGINAL BEFORE LINKS: path('', TemplateView.as_view(template_name='pricing/spark_base.html'), name='HOME'),
    path('logout/', logout)
]

reuse-data1/mm/urls.py
from django.contrib import admin
from django.urls import path


from mm.views import *  ##importing the MM app view

app_name='mm'

urlpatterns = [
    path('', mm, name='mm'), ## can be deleted later
    path('submit/', mmsubmit,name='mmsubmit'),
    path('rawdata/', rawdata, name='rawdata'),
    path('movement/', movement, name='movement'),
    path('movement_submit/', movement_submit, name='movement_submit'),

    path('stats/<slug:location>/', stats_location, name='stats_location'),

    path('stats/', stats, name='stats' ),
    path('raw/', raw, name='raw'),




]

reuse-data1/visitors/urls.py
from django.contrib import admin
from django.urls import path


from visitors.views import *

app_name='visitors'

urlpatterns = [

    path('submit/', submit, name='submit'),

    path('hourly/<slug:location>/', visitors_hourly, name='visitors_hourly'),
    path('<slug:location>/', VISITORS, name='VISITORS'),

    # path('capacity/', capacity, name='capacity'),


    # path('capacity_test/<slug:location>/', capacity_test, name='capacity_test'),
    # path('capacity_max_test/<slug:location>/', capacity_max_test, name='capacity_max_test'),


]

reuse-data1/visitors/models.py
from django.db import models

# Create your models here.


class Visitors(models.Model):
    timestamp = models.DateTimeField()
    count = models.IntegerField()
    location = models.CharField(max_length=64)
    capacity = models.FloatField(null=True)

class Site(models.Model):
    location = models.CharField(max_length=64)
    capacity = models.IntegerField()

reuse-data1/visitors/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, HttpResponseNotFound, JsonResponse

# Create your views here.

from visitors.models import Visitors
from django.db.models import Sum, Count, DateTimeField, Avg, Max
from django.db.models.functions import Trunc, Extract

from visitors.functions import useastern,useastern_start, useastern_end, start_end_date, capacity_generate

import pytz
import json
from datetime import datetime
import pandas as pd
from collections import defaultdict

from visitors.models import Visitors
from django.utils import timezone


def wants_json_response(request):
    fmt = request.GET.get('format', '')
    if fmt.lower() == 'json':
        return True
    accept_header = request.headers.get('Accept', '')
    return 'application/json' in accept_header.lower()



def submit(request):  #ASUME LOCATIONS ARE CORRECT
    #IF USER IS NOT AUTHENTICATED SEND THEM HOME!
    if not request.user.is_authenticated:
        return redirect('HOME')

# HARCOCDED LOCATIONS!!!!!!!!!!!!!!!!
    if 'location' in request.POST and str(request.POST['location']) not in ['IRC','TRC','DDO','RCH','TEST', '700-CABOOSE', 'TRC-DONATIONS' ,'700-WAREHOUSE']:
        location = 'TEST'
    else:
        location = request.POST['location']

    try:
        # flr_email = request.user.email
        count = int(request.POST['count'])
        if count > 10:
            count = 10
        if count < -10:
            count = -10
    except:
        return redirect('/visitors/test')
    ##############################
    if count != 0 :
        RECORD = Visitors(timestamp=timezone.now(),count=count,location=location)
        RECORD.save()
        capacity_generate(RECORD)

    return redirect('/visitors/' + location.lower() + '/')





def VISITORS(request, location=''):
    #IF USER IS NOT AUTHENTICATED SEND THEM HOME!
    if not request.user.is_authenticated:
        return redirect('HOME')
    # HARDCODED STUFF - LOCATION

    if location.strip() == '' or location.upper() not in ['IRC','TRC','RCH','DDO','TEST', '700-CABOOSE','TRC-DONATIONS','700-WAREHOUSE']:
        return redirect('HOME')
    else:
        location = location.upper()

    #HARDCODED
    capacity = {'IRC':140,'TRC':183,'RCH':175,'DDO':999,'TEST':999, '700-CABOOSE': 35, 'TRC-DONATIONS' : 999,'700-WAREHOUSE' : 38}[location]



    Visitors_here_today = Visitors.objects.filter(
        location=location,
        timestamp__range=(useastern_start(),useastern_end())
        )

    ################# Section to Make the Hours Box at the bottom
    hours_totals = defaultdict(int)
    hours_labels = {}
    for record in Visitors_here_today:
        if record.count > 0:
            hour_dt = useastern(record.timestamp).replace(minute=0, second=0, microsecond=0)
            hours_totals[hour_dt] += record.count
            hours_labels[hour_dt] = hour_dt.strftime("%I %p --")

    hourly_rows = [
        {'label': hours_labels[key], 'count': hours_totals[key]}
        for key in sorted(hours_totals.keys())
    ]

    if hourly_rows:
        info_df = pd.DataFrame([
            {'Hour of Day (Today)': row['label'], 'Total Visitors that Entered': row['count']}
            for row in hourly_rows
        ])
        info = info_df.to_html(index=False, classes="text-center table table-sm").replace("right;", "center;")
    else:
        info = '<p class="text-center text-muted">No visitor entries recorded today.</p>'
    ################# INFOSECTION GET HOURLY DATA

    render_dict = {
        'capacity': {'IRC':140,'TRC':183,'RCH':175,'DDO':999,'TEST':999,'700-CABOOSE': 35,'TRC-DONATIONS':999 ,'700-WAREHOUSE': 38}[location],
        'location' : location,

        'current' : Visitors_here_today.aggregate(Sum('count'))['count__sum'] or 0,
        'total_today' : Visitors_here_today.filter(count__gte=0).aggregate(Sum('count'))['count__sum'] or 0,
        'info': info,
        'hourly_rows': hourly_rows,
    }

    if wants_json_response(request):
        return JsonResponse({
            'location': location,
            'capacity': capacity,
            'current': render_dict['current'],
            'total_today': render_dict['total_today'],
            'hourly': hourly_rows,
        })

    return render(request, 'visitors/index.html',render_dict)















###########################################################################
# visitors_hourly VIEW - HOURLY STATISTICS
# v2.0

def visitors_hourly(request, location=''):

    #IF USER IS NOT AUTHENTICATED SEND THEM HOME!
    if not request.user.is_authenticated:
        return redirect('HOME')
    # HARDCODED STUFF - LOCATION
    if location.strip() == '' or location.upper() not in ['IRC','TRC','RCH','DDO','TEST', '700-CABOOSE','TRC-DONATIONS','700-WAREHOUSE']:
        return redirect('HOME')
    else:
        location = location.upper()



    start_date,end_date = start_end_date(request.GET)

    # Segment 1 : The Pivot table for the chart  ############################
    QUERY_1 = Visitors.objects.filter(location=location, count__gte=0, timestamp__range=(start_date,end_date)) \
        .annotate( tr_hour =Trunc('timestamp',kind='hour', tzinfo=pytz.timezone('US/Eastern'))) \
        .values('tr_hour').annotate(tr_hour_sum=Sum('count'))

    try:
        df = pd.DataFrame(data=list(QUERY_1),columns=list(QUERY_1[0].keys()))
        df['hour'] = df['tr_hour'].dt.hour
        df['date'] = df['tr_hour'].dt.date
        df_1 = df.pivot(index='date',columns='hour',values='tr_hour_sum'  ).fillna('')

    except:
        df_1 = pd.DataFrame(columns=['No Table Data in this range'])

    finally:
        # RETURN THE TABLE TO THE USER IF NEEDED !!!!!!!!!!!!!!!
        # PARSER SECTION
        if 'download' in request.GET:
            if request.GET['download'] == 'CSV':
                # PANDAS MANUAL RETURN THE OBJECT!
                response = HttpResponse(content_type='text/csv')
                response['Content-Disposition'] = 'attachment; filename=raw_data_export.csv'
                df_1.to_csv(path_or_buf=response)
                return response

        df_1_html = df_1.to_html(classes='table table-sm table-striped text-center')



    # Segment 2 : the BAR CHART by DAY OF WEEK  ############################
    QUERY_2 = Visitors.objects.filter(location=location, count__gte=0, timestamp__range=(start_date,end_date)) \
        .annotate(week_day_number = Extract('timestamp','week_day', tzinfo=pytz.timezone('US/Eastern'))) \
        .values('week_day_number').annotate(week_day_sum=Sum('count')).order_by('week_day_number')

    weekday_list = { 1:'Sunday', 2:'Monday', 3:'Tuesday', 4:'Wednesday', 5:'Thursday', 6:'Friday', 7:'Saturday'}

    chartJS_2 = {
                'type': 'bar',
                'data': {
                    'labels': [weekday_list[x['week_day_number']] for x in list(QUERY_2)],
                    'datasets': [{
                        'label': 'Visitor Total by WEEKDAY',
                        'data': [x['week_day_sum'] for x in QUERY_2],
                        'backgroundColor': 'rgba(0, 120, 0, 0.85)',
                        'borderWidth': 1
                    }]
                },
                'options': {
                    'scales': {
                        'yAxes': [{
                            'ticks': {
                                'beginAtZero': True
                            }
                        }]
                    }
                }
            }





    # Segment 3 : bar chart hour of the day  ############################

    QUERY_3 = Visitors.objects.filter(location=location, count__gte=0, timestamp__range=(start_date,end_date)) \
        .annotate(hour_number = Extract('timestamp','hour', tzinfo=pytz.timezone('US/Eastern'))) \
        .values('hour_number').annotate(hour_sum=Sum('count')).order_by('hour_number')


    chartJS_3 = {
                'type': 'bar',
                'data': {
                    'labels': [x['hour_number'] for x in list(QUERY_3)],
                    'datasets': [{
                        'label': 'Visitor Total by HOUR',
                        'data': [x['hour_sum'] for x in QUERY_3],
                        'backgroundColor': 'rgba(84,100,191,0.85)',
                        'borderWidth': 1
                    }]
                },
                'options': {
                    'scales': {
                        'yAxes': [{
                            'ticks': {
                                'beginAtZero': True
                            }
                        }]
                    }
                }
            }

    # Segment 4 : bar chart MONTHLY AGGREGATION  ############################

    QUERY_4 = Visitors.objects.filter(location=location, count__gte=0, timestamp__range=(start_date,end_date)) \
        .annotate(month_number = Extract('timestamp','month', tzinfo=pytz.timezone('US/Eastern'))) \
        .values('month_number').annotate(month_sum=Sum('count')).order_by('month_number')

    month_list = { 1:'Jan', 2:'Feb', 3:'Mar', 4:'Apr', 5:'May', 6:'Jun', 7:'Jul', 8:'Aug', 9:'Sep', 10:'Oct', 11:'Nov', 12:'Dec'}

    chartJS_4 = {
                'type': 'bar',
                'data': {
                    'labels': [ month_list[ x['month_number'] ] for x in list(QUERY_4)],
                    'datasets': [{
                        'label': 'Visitor Total by MONTH',
                        'data': [x['month_sum'] for x in QUERY_4],
                        'backgroundColor': 'rgba(242,170,82,0.85)',
                        'borderWidth': 1
                    }]
                },
                'options': {
                    'scales': {
                        'yAxes': [{
                            'ticks': {
                                'beginAtZero': True
                            }
                        }]
                    }
                }
            }


    # Render section :::::::::
    start_date_f = start_date.strftime('%Y-%m-%d')

reuse-data1/visitors/templates/visitors/capacity.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="noindex">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="https://cdn.pydata.org/bokeh/release/bokeh-2.1.1.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.pydata.org/bokeh/release/bokeh-widgets-2.1.1.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.pydata.org/bokeh/release/bokeh-tables-2.1.1.min.css"/>

    <title>(Private) - All Stores Capacity Utilization</title>
  </head>
  <body>

    <div class="nav bg-dark"><div class="container pb-3 pt-5 shadow-sm"><h3 class="row text-light">All Stores Visitor Statistics</h3></div></div>

    <!-- START DATE RANGE CONTAINER -->
    <div class="container pt-3">
    <form method="GET">
      <div class="row">
        <div class="col form-group"><label>Start Date:</label>
          <input id="start_date" name="start" type="date" class="form-control" value="{{start_date}}" min="2020-08-06" max="{{max_date}}">
        </div>
         <div class="col form-group"><label>End Date:</label>
           <input disabled id="end_date" name="end" type="date" class="form-control" value="{{end_date}}" min="2019-01-01" max="{{max_date}}">
         </div>
        <div class="col form-group"><label id="message_text">.</label><br>
          <input id="submit_button" type="submit" class="btn btn-success btn-block">
        </div>
      </div>
    </form>
    </div>
<!-- END DATE RANGE CONTAINER -->
    <div class="my-3"><br></div>

    <div align="center" class="container col">
      <h3 class="">Capacity Tracker by Time</h3>
      {{allstores_bokeh_html | safe}}

    </div>



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.4.0.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-tables-1.4.0.min.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-api.1.4.0.min.js"></script>
    {{allstores_bokeh_script | safe}}

  </body>
</html>

reuse-data1/visitors/templates/visitors/capacity_max_test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Capacity Test</title>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"> </script>
  </head>
  <body>
    <h1>{{location}} Capacity Stats</h1>
    <h3>Capacity Maximums by Hour/Weekday (Percentages %)</h3>
    <p>Note: This method is more prone to user submittion error, as the maximum capcity is taken per hour. Please refer to the capacity averages aggregation for a more accurate view.</p>
    <div id="chart1" height="600px" width="600px"></div>
    <h3>Capacity Maximums by Hour/Weekday (table data)</h3>
    {{table2 | safe}}
    <br>
    <br>
    <h3>Capacity Maximums by individual day</h3>
    {{table1 | safe}}
    <br>
    <br>
    <br>
    <br>







    <script type="text/javascript">
        var options = {
      chart: {
        'type': 'heatmap',
        'height': 500,
        'width' : 1080
      },
      // series: [{name: 'sales', data: [0,1,2,3,4,5,6,7,8,9]},{name: 'sales2', data: [-1,2,3,2,1,3,4,1,2,2]} ],
      series: {{series_list | safe}},
      xaxis: {
        categories: {{hours | safe}}
      },
      'colors':['#347532']
    }

    var chart1 = new ApexCharts(document.querySelector("#chart1"), options);

    chart1.render();
    </script>

  </body>
</html>

reuse-data1/visitors/templates/visitors/capacity_test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Capacity Test</title>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"> </script>
  </head>
  <body>
    <h1>{{location}} Capacity Stats</h1>
    <h3>Capacity Averages by Hour/Weekday (Percentages %)</h3>
    <div id="chart1" height="600px" width="600px"></div>
    <h3>Capacity Averages by Hour/Weekday (table data)</h3>
    {{table2 | safe}}
    <br>
    <br>
    <h3>Capacity Averages by individual day</h3>
    {{table1 | safe}}
    <br>
    <br>
    <br>
    <br>







    <script type="text/javascript">
        var options = {
      chart: {
        'type': 'heatmap',
        'height': 500,
        'width' : 1080
      },
      // series: [{name: 'sales', data: [0,1,2,3,4,5,6,7,8,9]},{name: 'sales2', data: [-1,2,3,2,1,3,4,1,2,2]} ],
      series: {{series_list | safe}},
      xaxis: {
        categories: {{hours | safe}}
      },
      'colors':['#347532']
    }

    var chart1 = new ApexCharts(document.querySelector("#chart1"), options);

    chart1.render();
    </script>

  </body>
</html>

reuse-data1/visitors/templates/visitors/hourly.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="noindex">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>(Private) - {{location}} Hourly Visitors</title>
  </head>
  <body>

    <div class="nav bg-dark"><div class="container pb-3 pt-5 shadow-sm"><h3 class="row text-light">{{location}} Hourly Visitors</h3></div></div>



    <!-- START DATE RANGE CONTAINER -->
    <div class="container pt-3">
    <form method="GET">
      <div class="row">
        <div class="col form-group"><label>Start Date:</label>
          <input id="start_date" name="start" type="date" class="form-control" value="{{start_date}}" min="2020-07-01" max="{{max_date}}">
        </div>
         <div class="col form-group"><label>End Date:</label>
          <input id="end_date" name="end" type="date" class="form-control" value="{{end_date}}" min="2020-07-01" max="{{max_date}}">
         </div>
        <div class="col form-group"><label id="message_text">.</label><br>
          <input id="submit_button" type="submit" class="btn btn-success btn-block">
        </div>
      </div>
    </form>
    </div>
<!-- END DATE RANGE CONTAINER -->
    <div class="my-3"><br></div>




    <div align="center" class="container my-5">
      <div class="row">
        <div class="col-md-6 my-3"><canvas id="chartJS_2"></canvas></div>
        <div class="col-md-6 my-3"><canvas id="chartJS_4"></canvas></div>
      </div>
    </div>

    <div align="center" class="container my-5">
      <canvas id="chartJS_3"></canvas>
    </div>

    <div align="center" class="container my-5">
      <h3 class="">Raw Table Data</h3><h5><a href="{{download_csv_link}}">(Download CSV)</a></h5>
      {{table | safe}}
    </div>




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha256-t9UJPrESBeG2ojKTIcFLPGF7nHi2vEc7f5A2KpH/UBU=" crossorigin="anonymous"></script>


    <!-- CHART JS -->
    <script>
    let ctx_2 = document.getElementById('chartJS_2').getContext('2d');
    let myChart_2 = new Chart(ctx_2, {{chartJS_2 | safe}} );

    let ctx_3 = document.getElementById('chartJS_3').getContext('2d');
    let myChart_3 = new Chart(ctx_3, {{chartJS_3 | safe}} );

    let ctx_4 = document.getElementById('chartJS_4').getContext('2d');
    let myChart_4 = new Chart(ctx_4, {{chartJS_4 | safe}} );

    </script>
    <!-- CHART JS -->


  </body>
</html>

reuse-data1/visitors/templates/visitors/index.html
{% load socialaccount %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="noindex">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'sp_src/css/modern.css' %}">
    <link rel="stylesheet" href="{% static 'frontend/colorwheel/index-Z_Kt6Jy-.css' %}">

    <title>(Private) - {{location}} Visitors Counter</title>
  </head>
  <body>

    <div class="nav" style="background:#153d77;">
      <div class="container pb-3 pt-5 shadow-sm">
        <div class="d-flex justify-content-between align-items-center text-light">
          <a href="{% url 'HOME' %}" class="btn btn-link text-light px-0">
            &larr; Back
          </a>
          <h3 class="m-0">{{location}} Visitors Counter</h3>
        </div>
      </div>
    </div>

    <div class="container mt-5 mb-3">

      <div
        id="visitors-root"
        data-endpoint="{% url 'visitors:VISITORS' location %}?format=json"
        data-submit-url="{% url 'visitors:submit' %}"
        data-csrf="{{ csrf_token }}"
        data-location="{{ location }}"
        data-user-email="{{ user.email }}"
        data-home-url="{% url 'HOME' %}"
      ></div>

      <noscript>
        <div class="alert alert-warning mt-4">
          This dashboard requires JavaScript. Enable it to use the modern interface. Showing legacy view instead.
        </div>
        <div class="row">
          <div class="col text-center">
            <h1 class="display-4 text-secondary">{{capacity}}</h1>
            <h5 class="mt-3 pb-5 text-secondary">Maximum Capacity<br><strong>{{location}}</strong></h5>
          </div>
          <div class="col text-center">
            <h1 class="text-center display-1">{{current}}</h1>
            <h5 class="text-center mt-3 pb-5">Visitors currently at {{location}}</h5>
          </div>
          <div class="col text-center">
            <h1 class="display-4 text-secondary">{{total_today}}</h1>
            <h5 class="mt-3 pb-5 text-secondary">Total visitors today</h5>
          </div>
        </div>
        <div class="mt-4">
          {{info | safe}}
        </div>
      </noscript>

    </div>





    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script type="module" src="{% static 'frontend/colorwheel/index-oGx19SVO.js' %}" defer></script>



  </body>
</html>