reuse-data1/djangoproject/urls.py
## This can be deleted later (this admin import)
from django.contrib import admin

from django.urls import path, include
from django.views.generic import TemplateView

from login.views import logout
from pricing.views import template_home



urlpatterns = [
    path('admin/', admin.site.urls), ## can be deleted later
    path('mm/',include('mm.urls')),
    path('idh/',include('idh.urls')),
    path('reports/',include('reports.urls')),
    path('shopify/', include('shopify.urls')),
    path('visitors/',include('visitors.urls')),
    path('pricing/', include('pricing.urls')),
    path('giftcardportal/', include('qbgiftcard.urls')),

    path('accounts/', include('allauth.urls')),

    path('', template_home, name='HOME'),
    # ORIGINAL BEFORE LINKS: path('', TemplateView.as_view(template_name='pricing/spark_base.html'), name='HOME'),
    path('logout/', logout)
]

reuse-data1/mm/urls.py
from django.contrib import admin
from django.urls import path


from mm.views import *  ##importing the MM app view

app_name='mm'

urlpatterns = [
    path('', mm, name='mm'), ## can be deleted later
    path('submit/', mmsubmit,name='mmsubmit'),
    path('rawdata/', rawdata, name='rawdata'),
    path('movement/', movement, name='movement'),
    path('movement_submit/', movement_submit, name='movement_submit'),

    path('stats/<slug:location>/', stats_location, name='stats_location'),

    path('stats/', stats, name='stats' ),
    path('raw/', raw, name='raw'),




]

reuse-data1/mm/models.py
from django.db import models


class RawMaterialMovement(models.Model):
    rName = models.CharField(max_length=128)
    rDate = models.DateField()
    rMode = models.CharField(max_length=128)
    rTrips = models.CharField(max_length=128)
    rOrigin = models.CharField(max_length=128)
    rOriginLocation = models.CharField(max_length=128)
    rDestination = models.CharField(max_length=128)
    rDestinationLocation = models.CharField(max_length=128)
    rMaterial = models.CharField(max_length=2048)
    rHidden = models.CharField(max_length=1024)
    rTimestamp = models.CharField(max_length=128)

    def __str__(self):
        return str(self.rTimestamp)

    def __all__(self):
        return {
            'rName' : self.rName,
            'rDate' : self.rDate,
            'rTrips' : self.rTrips,
            'rMode' : self.rMode,
            'rOrigin' : self.rOrigin,
            'rOriginLocation' : self.rOriginLocation,
            'rDestination' : self.rDestination,
            'rDestinationLocation' : self.rDestinationLocation,
            'rMaterial' : self.rMaterial,
            'rHidden' : self.rHidden,
            'rTimestamp' : self.rTimestamp,
            }

class ExpandedMaterialMovement(models.Model):
        eName = models.CharField(max_length=128)
        eDate = models.DateField()
        eMode = models.CharField(max_length=128)
        eTrips = models.CharField(max_length=128)
        eOrigin = models.CharField(max_length=128)
        eOriginLocation = models.CharField(max_length=128)
        eDestination = models.CharField(max_length=128)
        eDestinationLocation = models.CharField(max_length=128)
        eTimestamp = models.CharField(max_length=128)
        eMaterial = models.CharField(max_length=128)
        ePallets = models.DecimalField(max_digits=8,decimal_places=2, default='0.00')
        # ePalletsX = models.CharField(max_length=128)
        eTripID = models.CharField(max_length=128)

        # REMOVED rMaterial :)
        # REMOVED rHidden :)
        # ADDED : ePallets + eMaterial + eTripID(SHA256 HASH)





###################################################
#  2021 UPGRADE
###################################################

# First : The locations table

# Second : The simple movement table


class Movement(models.Model):
    location_choices = [('I','IRC'),('T','TRMC'),('7','700'),('D','DOT')]  # COPIED + HARCODED FROM PRICING
    type_choices = [('D','Donations'),('O','Overflow'),('P','Processing'),('S','Salesfloor')]

    origin_type = models.CharField(max_length=1, choices=type_choices)
    origin_location = models.CharField(max_length=1, choices=location_choices)
    destination_type = models.CharField(max_length=1, choices=type_choices)
    destination_location = models.CharField(max_length=1, choices=location_choices)

    staff_id = models.CharField(max_length=32)
    timestamp = models.DateTimeField(auto_now_add=True)


class Pallet(models.Model):
    movement = models.ForeignKey(Movement, on_delete=models.PROTECT)
    product_type = models.ForeignKey('pricing.ProductType', on_delete=models.PROTECT)
    quantity = models.DecimalField(max_digits=5,decimal_places=2)

reuse-data1/mm/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.timezone import datetime
from .models import RawMaterialMovement, ExpandedMaterialMovement
import requests
import json
from .functions import ExpansionFunction, expand_locations_in_order


# 2021 Extention
from mm.models import Pallet,Movement
from pricing.models import ProductType
from visitors.functions import start_end_date

from datetime import timedelta
from django.utils import timezone
from django.db.models import Sum, F, FloatField, ExpressionWrapper

def mm(request):
    return redirect('mm:movement')
    #IF USER IS NOT AUTHENTICATED SEND THEM HOME!
    if not request.user.is_authenticated:
        return redirect('HOME')

    return_dict = {
        'tDate' : str(datetime.today())[0:10],          #################NEED TO FIGURE OUT THE TIMEZONE DIFF!!!
        'tTimestamp' : str(datetime.now().timestamp()),
        'tName' : request.user.email,
        }
    return  render(request, 'mm/material.html',return_dict)
    # return HttpResponse()




def mmsubmit(request):
    if request.method == 'POST':

        mFormData = {
        'rName' : request.POST['mName'],
        'rDate' : request.POST['mDate'],
        'rMode' : request.POST['mMode'],
        'rTrips' : request.POST['mTrips'],
        'rOrigin' : request.POST['mOrigin'],
        'rOriginLocation' : request.POST['mOriginLocation'],
        'rDestination' : request.POST['mDestination'],
        'rDestinationLocation' : request.POST['mDestinationLocation'],
        'rMaterial' : request.POST['mMaterial'],
        'rHidden' : request.POST['mHidden'],
        'rTimestamp' : request.POST['mTimestamp'],
        }


        #Submit to the Django Database
        Submission = RawMaterialMovement(**mFormData)
        RawMaterialMovement.objects.create(**mFormData).save()



        # Create a text file
        with open('raw_log/' + str(mFormData['rTimestamp']) ,'w') as temp:
            temp.write(json.dumps(mFormData))


        # Submit to Google Sheets Redundancy
        googleurl = 'https://docs.google.com/forms/d/e/1FAIpQLSfXjO5RPjy9nz4M8x52CeVtaynOmXkd_3KnXtO6I3MHE3O0Aw/formResponse'
        googleparams = {
            'entry.2054024210' : mFormData['rName'],
            'entry.781229162' : mFormData['rDate'],
            'entry.540449382' : mFormData['rMode'],
            'entry.1201600051' : mFormData['rTrips'],
            'entry.1978589283' : mFormData['rOrigin'],
            'entry.392818040' : mFormData['rOriginLocation'],
            'entry.1847268034' : mFormData['rDestination'],
            'entry.745648505' : mFormData['rDestinationLocation'],
            'entry.2044658746' : mFormData['rMaterial'],
            'entry.1404056945' : mFormData['rHidden'],
            'entry.2092600452' : mFormData['rTimestamp'],
        }

        #GOOGLE FORM SUBMIT OFF
        googlerequest = requests.post(googleurl, data=googleparams)

        #THIS iS WHERE WE EXPAND STUFF


        # MESSAGE = ExpansionFunction(mFormData)
        for i in ExpansionFunction(mFormData):
            if str(mFormData['rHidden']).strip().lower() != 'test':
                ExpandedMaterialMovement.objects.create(**i).save()


        # MESSAGE = RawMaterialDict


        return render(request, 'mm/submission.html',{'message':Submission })

    else:
        return redirect('../')
    return HttpResponse(x)



from .models import ExpandedMaterialMovement

def rawdata(request):
    E = ExpandedMaterialMovement.objects.all()
    print('\n\n\n\n',dict(vars(E[0])).keys(),'\n\n\n\n')
    for i in E:
        temp = dict(vars(i))
        for j in temp:
            print(temp[j], end=',')
        print()
    return HttpResponse('WORKING')






################################################################
# 2021 REDO OF MATERIAL Movement
################################################################


def movement(request):
    #IF USER IS NOT AUTHENTICATED SEND THEM HOME!
    if not request.user.is_authenticated:
        return redirect('HOME')

    # RECORDS = Movement.objects.filter(staff_id = str(request.user.email).split('@')[0])\
        # .order_by('-timestamp')[0:20]
    RECORDS = Pallet.objects.filter(\
        movement__staff_id = str(request.user.email).split('@')[0],
        movement__timestamp__range=( timezone.now()-timedelta(days=7) ,  timezone.now()  )   )\
        .values('id','movement__timestamp','movement__origin_type','movement__origin_location','movement__destination_type','movement__destination_location','product_type__product_type','quantity')

    return_dict = {
        'product_type_list' : [[i.product_type,i.id] for i in ProductType.objects.all().order_by('product_type')],
        'header_subtitle': '',
        'RECORDS' : RECORDS,

    }
    # IF THERE WAS A RECENT TRANSACTION, THEN PLEASE ADD IN A RECORD FOR THAT

    return render(request,'mm/movement.html', return_dict)




####################################
# MOVEMENT SUBMISSION Form
####################################

def movement_submit(request):
    origin_location = request.POST.get('origin_location')
    origin_type = request.POST.get('origin_type')
    destination_location = request.POST.get('destination_location')
    destination_type = request.POST.get('destination_type')
    material_list = request.POST.get('pallets')
    pallets_raw = json.loads(material_list)

    # FLATTEN LIST
    pallets = dict()
    for i in pallets_raw:
        if i[0] in pallets:
            pallets[i[0]] += float(i[1])
        else:
            pallets[i[0]] = float(i[1])

    staff_id = str(request.user.email).split('@fingerlakesreuse.org')[0]

    # FIRST SUBMIT TO MOVEMENT # DB
    movement_id = Movement.objects.create(
        origin_type=origin_type, origin_location=origin_location, destination_type=destination_type, destination_location=destination_location, staff_id=staff_id
    )

    # SUBMIT THE FLATTEN LIST ONE BY ONE TO THE # DB:
    pallet_db = Pallet.objects
    for i in pallets:
        pallet_db.create(movement=movement_id, product_type=ProductType.objects.get(id=int(i))   ,quantity=pallets[i])

    # return HttpResponse( f'{origin_type}, {origin_location}, {destination_type}, {destination_location}, {pallets}')
    return redirect('mm:movement')








####################################
# STATS - INITIAL
####################################
def stats(request):
    #IF USER IS NOT AUTHENTICATED SEND THEM HOME!
    if not request.user.is_authenticated:
        return redirect('HOME')

    start_date, end_date = start_end_date(request.GET)

    P = Pallet.objects.filter(movement__timestamp__range=(start_date,end_date))

    #Initial Breakdowns
    P_donations_received = P.filter(movement__origin_type='D')
    P_donations_received_breakdown = expand_locations_in_order( P.values('movement__origin_location').annotate(Pallets=Sum('quantity', output_field=FloatField())) ,'movement__origin_location' )
    P_donations_received_total = P_donations_received.aggregate(donations_received=Sum('quantity'))['donations_received']
    if P_donations_received_total == None: P_donations_received_total = 0


    P_sent_to_overflow = P.filter( movement__destination_type='O')
    P_sent_to_overflow_breakdown = expand_locations_in_order( P.values('movement__destination_location').annotate(Pallets=Sum('quantity', output_field=FloatField()))  ,'movement__destination_location')
    P_sent_to_overflow_total = P_sent_to_overflow.aggregate(sent_to_overflow=Sum('quantity'))['sent_to_overflow']
    if P_sent_to_overflow_total == None: P_sent_to_overflow_total = 0

    P_pulled_from_overflow = P.filter(movement__origin_type='O')
    P_pulled_from_overflow_total = P_pulled_from_overflow.aggregate(pulled_from_overflow=Sum('quantity'))['pulled_from_overflow']
    if P_pulled_from_overflow_total == None: P_pulled_from_overflow_total = 0

    P_processing_volume = P.filter(movement__destination_type__in=['P','S']).exclude(movement__origin_type='P') ######### NOTE: ADDING ORIGIN EXCLUSION TO AVOID PROCESSING>>>>SALESFLOOR DOUBLE REPORTING!!!!!!!!!!!!!!
    P_processing_volume_total = P_processing_volume.aggregate(processing_volume=Sum('quantity'))['processing_volume']
    if P_processing_volume_total == None: P_processing_volume_total = 0


    return_dict = {
        'start_date': start_date.strftime('%Y-%m-%d'),
        'end_date': end_date.strftime('%Y-%m-%d'),

        #Crunch Totals
        'donations_received' : P_donations_received_total,
        'sent_to_overflow' : P_sent_to_overflow_total,
        'pulled_from_overflow' : P_pulled_from_overflow_total,
        'processing_volume' : P_processing_volume_total,

        #Breakdown Tables
        'donations_received_breakdown' : P_donations_received_breakdown,
        'sent_to_overflow_breakdown' : P_sent_to_overflow_breakdown,

        #Matrix Diagram! - Not effecient
        'irc_irc': P.filter(movement__origin_location='I', movement__destination_location='I').aggregate(Total=Sum('quantity'))['Total'],
        'irc_trmc': P.filter(movement__origin_location='I', movement__destination_location='T').aggregate(Total=Sum('quantity'))['Total'],
        'irc_dot': P.filter(movement__origin_location='I', movement__destination_location='D').aggregate(Total=Sum('quantity'))['Total'],
        'trmc_irc': P.filter(movement__origin_location='T', movement__destination_location='I').aggregate(Total=Sum('quantity'))['Total'],
        'trmc_trmc': P.filter(movement__origin_location='T', movement__destination_location='T').aggregate(Total=Sum('quantity'))['Total'],
        'trmc_dot': P.filter(movement__origin_location='T', movement__destination_location='D').aggregate(Total=Sum('quantity'))['Total'],
        'dot_irc': P.filter(movement__origin_location='D', movement__destination_location='I').aggregate(Total=Sum('quantity'))['Total'],
        'dot_trmc': P.filter(movement__origin_location='D', movement__destination_location='T').aggregate(Total=Sum('quantity'))['Total'],

reuse-data1/mm/templates/mm/movement.html
{% extends 'pricing/spark_base.html' %}

{% block title %}Material Movement Form - v2 (2021){% endblock %}


{% block header_title %}Material Movement Form - v2 (2021){% endblock %}

{% block header_subtitle %}{{ header_subtitle }}{% endblock %}

{% block active_link %}
{% endblock %}
{% load tz %}



{% block content %}
<div class="row">
  <div class="col-md-6 col-sm-12">
    <div class="card pt-3">
      <div class="card-body">
      <h3>Origin (FROM):</h3>
      <div class="row">
        <div class="col form-group mt-3">
            <button id="origin_donations" type="button" class="target_origin_type btn btn-lg btn-dark ">Donations</button>
            <button id="origin_overflow" type="button" class="target_origin_type btn btn-lg btn-outline-dark ">Overflow</button>
            <button id="origin_processing" type="button" class="target_origin_type btn btn-lg btn-outline-dark ">Processing</button>
            <!-- <button id="salesfloor" type="button" class="btn btn-lg btn-outline-dark target_origin_type">Sales Floor</button> -->
        </div>
       </div>
      <div class="row">
        <div class="col form-group mt-3">
          <h4>Location:</h4>
          <button id="origin_irc" type="button" class="target_origin_location btn btn-lg btn-dark">IRC</button>
          <button id="origin_trmc" type="button" class="target_origin_location btn btn-lg btn-outline-dark">TRMC</button>
          <button id="origin_700" type="button" class="target_origin_location btn btn-lg btn-outline-dark">DOT</button>
        </div>
      </div>


			</div>
		</div>
  </div>
  <div class="col-md-6 col-sm-12">
    <div class="card pt-3">
      <div class="card-body">
      <h3>Destination (TO):</h3>
      <div class="row">
        <div class="col form-group mt-3">
            <!-- <button id="" type="button" class="btn btn-lg btn-outline-dark" disabled="True">Donations</button> -->
            <button id="destination_overflow" type="button" class="target_destination_type btn btn-lg btn-dark">Overflow</button>
            <button id="destination_processing" type="button" class="target_destination_type btn btn-lg btn-outline-dark">Processing</button>
            <button id="destination_salesfloor" type="button" class="target_destination_type btn btn-lg btn-outline-dark">Sales Floor</button>
        </div>
       </div>
      <div class="row">
        <div class="col form-group mt-3">
          <h4>Location:</h4>
          <button id="destination_irc" type="button" class="target_destination_location btn btn-lg btn-dark">IRC</button>
          <button id="destination_trmc" type="button" class="target_destination_location btn btn-lg btn-outline-dark">TRMC</button>
          <button id="destination_700" type="button" class="target_destination_location btn btn-lg btn-outline-dark">DOT</button>
        </div>
      </div>


			</div>
		</div>
  </div>

</div>
<div class="row">
  <div class="col"></div>
  <div class="col-md-12 col-lg-10">
    <div class="card pt-3">
      <div class="card-body">
      <div id="target_container">
        <div class="row target_pallet_row pt-1">
           <div class="col"><select class="form-control target_row_material" ><option>BOOKS</option><option>MDIA</option></select></div>
           <div class="col"><input type="number" min="0.25" step="0.25" class="form-control target_row_quantity" max="10" value="0.25"></div>
           <div class="col form-group">
             <button type="button" class="btn btn-success target_row_del">DEL</button>
             <button type="button" class="ml-2 btn btn-outline-success target_row_add">+ Add Row</button></div>
        </div>
      </div>
      <div class="row">
        <form id="target_form" action="{% url 'mm:movement_submit' %}"  method="POST">
        {% csrf_token %}
        <input type="hidden" id="origin_type" name="origin_type" value="">
        <input type="hidden" id="origin_location" name="origin_location" value="">
        <input type="hidden" id="destination_type" name="destination_type" value="">
        <input type="hidden" id="destination_location" name="destination_location" value="">
        <input type="hidden" id="pallets" name="pallets" value="">
        <div class="col pt-3"><button id="target_submit" type="button" class="btn btn-lg btn-primary btn-block">Submit</button></div>
        </form>
      </div>
      </div>
    </div>
  </div>
  <div class="col"></div>
</div>


<div class="row mt-3">
  <div class="col-12">
    <div class="card pt-2 mb-2">
      <div class="card-header">
				<h5 class="card-title">Material Movement Submission History (Last 7 days) for <strong>{{request.user.email}}</strong></h5>
				<!-- <h6 class="card-subtitle text-muted">This section is still being developed and will be more descriptive in a few days!</h6> -->
			</div>
      <div class="card-body">
        <div id="targetTable">
          <table id="mainTable" class="table table-sm"><thead><tr><th>Record ID</th><th>Date/Time</th><th>Origin Type</th><th>Origin Location</th><th>Destination Type</th><th>Destination Location</th><th>PRODUCT TYPE</th><th>Pallets</th></tr></thead>
            <tbody>
              {% for i in RECORDS %}
                <tr>
                  <td>{{i.id}}</td>
                  <td>{% timezone "US/Eastern" %}{{i.movement__timestamp}}{% endtimezone %}</td>
                  <td>{{i.movement__origin_type}}</td>
                  <td>{{i.movement__origin_location}}</td>
                  <td>{{i.movement__destination_type}}</td>
                  <td>{{i.movement__destination_location}}</td>
                  <td>{{i.product_type__product_type}}</td>
                  <td>{{i.quantity}}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>



{% endblock %}



{% block javascript_end %}
<script type="text/javascript">

// RENDER THE LIST OF PRODUCT TYPES WITH THEIR IDS
product_type_list = {{product_type_list | safe}}
$('.target_row_material').html('')
for(i=0;i<product_type_list.length;i++){
  $('.target_row_material').append('<option value="' + product_type_list[i][1] +'">' + product_type_list[i][0] + '</option>')
}

function function_origin_type(){
  $('.target_origin_type').removeClass('btn-outline-dark')
  $('.target_origin_type').removeClass('btn-dark')
  $('.target_origin_type').addClass('btn-outline-dark')
  $(this).addClass('btn-dark')
}
function function_origin_location(){
  $('.target_origin_location').removeClass('btn-outline-dark')
  $('.target_origin_location').removeClass('btn-dark')
  $('.target_origin_location').addClass('btn-outline-dark')
  $(this).addClass('btn-dark')
}

function function_destination_type(){
  $('.target_destination_type').removeClass('btn-outline-dark')
  $('.target_destination_type').removeClass('btn-dark')
  $('.target_destination_type').addClass('btn-outline-dark')
  $(this).addClass('btn-dark')
}
function function_destination_location(){
  $('.target_destination_location').removeClass('btn-outline-dark')
  $('.target_destination_location').removeClass('btn-dark')
  $('.target_destination_location').addClass('btn-outline-dark')
  $(this).addClass('btn-dark')
}


// Listners
$('.target_origin_type').on('click', function_origin_type)
$('.target_origin_location').on('click', function_origin_location)
$('.target_destination_type').on('click', function_destination_type)
$('.target_destination_location').on('click', function_destination_location)

// Initialize one material row @ Page Start
material_row = $('#target_container').html()
$('.target_row_add').on('click', AddRow)
$('.target_row_del').on('click', DelRow)
TrimButtons()

function TrimButtons(){
  row_length = $('.target_row_del').length
  if(row_length == 1){
    $('.target_row_del').eq(0).prop('disabled', 'true')
  }
  else{
    $('.target_row_del').removeAttr('disabled')
    for(i=row_length-2;i>=0;i--){
      $('.target_row_add').eq(i).css('visibility','hidden')
    }
  }
  $('.target_row_add').eq(row_length-1).css('visibility','visible')
}

function AddRow(){
  $('#target_container').append( material_row)
  $('.target_row_add').off('click')
  $('.target_row_add').on('click', AddRow)
  $('.target_row_del').off('click')
  $('.target_row_del').on('click', DelRow)
  TrimButtons()
}

function DelRow(){
  index_to_delete = $(this).index('.target_row_del')
  $('.target_pallet_row').eq(index_to_delete).remove()
  TrimButtons()
}

// SUBMIT BUTTON LISTENER / FUNCTION
$('#target_submit').on('click', function(){

  $('#origin_type').attr('value',  $('.target_origin_type.btn-dark').html()[0].toUpperCase()  )

  $('#origin_location').attr('value',$('.target_origin_location.btn-dark').html()[0].toUpperCase())
  $('#destination_type').attr('value',$('.target_destination_type.btn-dark').html()[0].toUpperCase())
  $('#destination_location').attr('value',$('.target_destination_location.btn-dark').html()[0].toUpperCase())

  // STRINGIFY THE MATERIAL LIST
  material_list = []
  for(i=0;i< $('.target_pallet_row').length ;i++){
     material_list.push( [$('.target_row_material').eq(i).val(), $('.target_row_quantity').eq(i).val()]  )
  }
  $('#pallets').val(JSON.stringify(material_list))
  // REMEMBER TO DO CHECKING HERE)
  // SUBMIT THE FORM
  $("#target_form").submit()

})


// TEXT EXPANSION AND CHECK FOR LATEST ONLY IF THE RECORD COUNT IS MORE THAN 1 - indicating a recent record
text_expansion = { 'D':'Donation', 'O': 'Overflow', 'P': 'Processing', 'S':'Salesfloor' ,'I':'IRC','T':'TRMC','7':'700' }
records_count = $('#mainTable tbody tr').length
if(records_count >= 1){

}



</script>

{% endblock %}

reuse-data1/mm/templates/mm/overflow.html
{% extends 'pricing/spark_base.html' %}

{% block title %}Overflow State{% endblock %}


{% block header_title %}Overflow State{% endblock %}


{% block active_link %}
{% endblock %}



{% block content %}

<div class="row">
  <div class="col-md-6 col-sm-12">
    <div class="card pt-3">
      <div class="card-body">
      <h3>TITLE</h3>
      <div class="row">
        <div class="col form-group mt-3">
            <!-- <button id="salesfloor" type="button" class="btn btn-lg btn-outline-dark target_origin_type">Sales Floor</button> -->
        </div>
       </div>
      </div>
    </div>
  </div>
</div>



{% endblock %}



{% block javascript_end %}

{% endblock %}

reuse-data1/mm/templates/mm/raw.html
{% extends 'pricing/spark_base.html' %}

{% block title %}PRIVATE / WIP - Material Movement - RAW{% endblock %}
{% block header_title %}PRIVATE / WIP - Material Movement - RAW{% endblock %}

{% load tz %}
{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
      <form method="GET">
        <p>Please select the date range:</p>
        <div class="row">
          <!-- <div class="row"> -->
          <div class="col">
            <div class="form-group">
    					<!-- <label class="form-label">Start Date</label> -->
              <input class="form-control" type="date" name="start" value="{{start_date}}">
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <input class="form-control" type="date" name="end" value="{{end_date}}">
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <button class="form-control btn btn-primary btn-md" type="submit">SUBMIT</button>
            </div>
          </div>
  			</div>
      </form>
      </div>
    </div>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <div class="card pt-2 mb-2 text-center">
      <div class="card-header"><h3 class="card-title">Material Movement Between Sites</h3><h6 class="card-subtitle text-muted"></h6></div>
      <div class="card-body">
        <div id="targetTable">

          <table id="mainTable" class="table table-sm"><thead><tr><th>Staff ID</th><th>Date/Time</th><th>Origin Type</th><th>Origin Location</th><th>Destination Type</th><th>Destination Location</th><th>PRODUCT TYPE</th><th>Pallets</th></tr></thead>
            <tbody>
              {% for i in RECORDS %}
                <tr>
                  <td>{{i.movement__staff_id}}</td>
                  <td>{% timezone "US/Eastern" %}{{i.movement__timestamp | date:"SHORT_DATETIME_FORMAT"}}{% endtimezone %}</td>
                  <td>{{i.movement__origin_type}}</td>
                  <td>{{i.movement__origin_location}}</td>
                  <td>{{i.movement__destination_type}}</td>
                  <td>{{i.movement__destination_location}}</td>
                  <td>{{i.product_type__product_type}}</td>
                  <td>{{i.quantity}}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>


        </div>
      </div>
    </div>
  </div>
</div>



{% endblock %}



{% block javascript_end %}

<script type="text/javascript">
  $('#mainTable').DataTable({dom:'Bfrtip', 'pageLength': 50 ,buttons:['copy','csv','print']})
</script>

{% endblock %}

reuse-data1/mm/templates/mm/submission.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
   <head>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <meta charset="utf-8">
      <title>ReUse Material Movement Form</title>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
   </head>
   <body>
      <nav class="navbar navbar-dark bg-dark"><span class="navbar-brand mb-0 h1"><div class="container" >ReUse Material Movement Form</div></span></nav>
      <div class="container">
         <p></p>
      </div>
      <div class="container">
            <div id="outerForm">
                <h2><div align="center"><br>Your submission was successful!<br><br>THANK YOU!<br></div><br></h2><br>
            </div>
          <div class="row">
             <div class="col"><form method="get" action="../"><button id="SubmitAnother" type="submit" class="btn btn-lg btn-success btn-block">Submit Another</button></form></div>
          </div>
          <br><br><br><p style="color:grey"><strong>Submission Timestamp: </strong>{{message}}</p>
      </div>
      <div class="container" style="margin-top:3%;">
      </div>
   </body>
</html>