reuse-data1/djangoproject/urls.py
## This can be deleted later (this admin import)
from django.contrib import admin

from django.urls import path, include
from django.views.generic import TemplateView

from login.views import logout
from pricing.views import template_home



urlpatterns = [
    path('admin/', admin.site.urls), ## can be deleted later
    path('mm/',include('mm.urls')),
    path('idh/',include('idh.urls')),
    path('reports/',include('reports.urls')),
    path('shopify/', include('shopify.urls')),
    path('visitors/',include('visitors.urls')),
    path('pricing/', include('pricing.urls')),
    path('giftcardportal/', include('qbgiftcard.urls')),

    path('accounts/', include('allauth.urls')),

    path('', template_home, name='HOME'),
    # ORIGINAL BEFORE LINKS: path('', TemplateView.as_view(template_name='pricing/spark_base.html'), name='HOME'),
    path('logout/', logout)
]

reuse-data1/mm/urls.py
from django.contrib import admin
from django.urls import path


from mm.views import *  ##importing the MM app view

app_name='mm'

urlpatterns = [
    path('', mm, name='mm'), ## can be deleted later
    path('submit/', mmsubmit,name='mmsubmit'),
    path('rawdata/', rawdata, name='rawdata'),
    path('movement/', movement, name='movement'),
    path('movement_submit/', movement_submit, name='movement_submit'),

    path('stats/<slug:location>/', stats_location, name='stats_location'),

    path('stats/', stats, name='stats' ),
    path('raw/', raw, name='raw'),




]

reuse-data1/qbgiftcard/urls.py
from django.urls import path

from qbgiftcard.views import *

app_name='qbgiftcard'

urlpatterns = [
    path('', qbgiftcardhome, name='qbgiftcardhome'),

    path('results/', results, name='results'),

    path('lookup/', lookup, name='lookup'),

    # path('printlabel', printlabel, name='printlabel')

]

reuse-data1/qbgiftcard/models.py
from django.db import models

# Create your models here.
class GiftCard(models.Model):
    first_name = models.CharField(max_length = 128, default='', blank=True)
    last_name = models.CharField(max_length = 128, default='', blank=True)
    phone = models.CharField(max_length = 16, default='', blank=True)
    email = models.CharField(max_length = 256, default='', blank=True)
    giftcard = models.CharField(max_length = 256, default='')
    initial_balance = models.DecimalField(max_digits = 6, decimal_places = 2, default = '0.0')

    STATUS_CHOICES = (('i','initial'),('q','qbgiftcard'),('u','upgraded'),('r','remap'))
    status = models.CharField(default = 'i', max_length = 1, choices = STATUS_CHOICES)

    timestamp_created = models.DateTimeField(auto_now_add = True)
    timestamp_updated = models.DateTimeField(auto_now = True)

    UID = models.IntegerField(default=-1)
    LINK = models.CharField(max_length = 129, default='')


    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class AccessLog(models.Model):
    staff_id = models.CharField(max_length = 32)
    giftcard = models.ForeignKey(GiftCard, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f'{self.staff_id}, {self.timestamp}'

reuse-data1/qbgiftcard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
# Create your views here.

from qbgiftcard.models import GiftCard

from qbgiftcard.models import *

from json import dumps

from datetime import datetime, timedelta
import pytz

from django.db.models.functions import Trunc







def qbgiftcardhome(request):
    G = GiftCard.objects.all()
    customer_dict = []
    for i in G:
        customer_dict.append([i.id, i.first_name, i.last_name, i.phone, i.email ])
    return render(request, 'qbgiftcard/default1.html', {'customer_dict': dumps(customer_dict)})


def lookup(request):
    if not request.user.is_authenticated:
        return redirect('HOME')
    try:
        x = int(request.POST['customer_id'])
        g = GiftCard.objects.get(id=x)
        staff_id = str(request.user.email).split('@fingerlakesreuse.org')[0]
        AccessLog.objects.create(staff_id=staff_id, giftcard=g)
    except:
        return HttpResponse('<h1>error occured</h1>')
    return redirect('qbgiftcard:results')




def results(request):
    if not request.user.is_authenticated:
        return redirect('HOME')
    try:
        staff_id = str(request.user.email).split('@fingerlakesreuse.org')[0]
        last_record = AccessLog.objects.filter(staff_id=staff_id).order_by('-timestamp')[0]
        gift_card_record = GiftCard.objects.get(id=last_record.giftcard_id)
        gift_card_code = gift_card_record.giftcard.replace(' ','')
        gift_card_name = f'{gift_card_record.last_name}, {gift_card_record.first_name}'



        access_log = AccessLog.objects.filter(giftcard_id=last_record.giftcard_id).order_by('-timestamp')[:100]\
            .annotate(DATE_TIME = Trunc('timestamp', kind='second', tzinfo=pytz.timezone('US/Eastern')))\
            .values('DATE_TIME','staff_id')

        for i in access_log:
            i['DATE_TIME'] = datetime.strftime(i['DATE_TIME'],'%b %d, %Y - %I:%M %p')

    except:
        print('ERROR')
        pass
    return render(request, 'qbgiftcard/lookup1.html', {'gift_card_code': gift_card_code, 'gift_card_name': gift_card_name, 'access_log':access_log})

reuse-data1/qbgiftcard/templates/qbgiftcard/default1.html
{% extends 'pricing/spark_base.html' %}





{% block title %}Quickbooks Gift Cards - LOOKUP{% endblock %}


{% block header_title %}Quickbooks Gift Cards - LOOKUP{% endblock %}



{% block active_link %}

{% endblock %}



{% block content %}



<div class="row">
	<div class="col-12 col-xl-9">

    <div class="card">
			<div class="card-header">
				<h5 class="card-title">Select the Quickbooks POS customer's Temporary Code</h5>
				<h6 class="pt-3 card-subtitle text-muted">Note: This is a temporary system to pull giftcard codes for customers in Quickbooks POS. New giftcards will be issued directly to customers and are printable at the register</h6>
			</div>
			<div class="card-body">
				<form action="{% url 'qbgiftcard:lookup' %}" method="POST"><!--COMMENT -->{% csrf_token %}<!--COMMENT -->
					<div class="form-group">
						<label class="form-label">Customer Name (Quikcbooks POS)</label><br>
						<select name="customer_id" id="customer_id" required>
              <option selected='true' disabled='true'>(Please select one)</option>
            </select>
					</div>
					<div class="form-group pt-3 pb-3">
            <p class="pt-1">Staff ID: <strong>{{request.user.email}}</strong></p>
						<label class="custom-control custom-checkbox">
							<input id="confirm_checkbox" type="checkbox" required="true" class="custom-control-input">
							<span class="custom-control-label">Confirm selection - Access of this giftcard will be logged.</span>
						</label>
					</div>
					<button id="submit_button" type="submit" class="btn btn-primary">View Giftcard Code</button>
				</form>
			</div>
    </div>


    <div class="accordion" id="accordionExample">
			<div class="card">
				<div class="card-header" id="headingOne">
					<h5 class="card-title my-2">
						<a href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="collapsed">Manually Select from list  - (Using the Search Box) </a>
					</h5>
				</div>
				<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample" style="">
					<div class="card-body">
            <table class="table" id="mainTable">
							<thead>
								<tr>
									<th style="width:40%;">Name</th>
									<th style="width:25%">Phone</th>
									<th class="d-none d-md-table-cell" style="width:25%">Email</th>
									<th>Select</th>
								</tr>
							</thead>
							<tbody id='customer_table'>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}




{% block javascript_end %}

<script type="text/javascript">
  let customer_dict = {{customer_dict | safe}}

  // Rend the dropdown and table
  for(i=0;i<customer_dict.length;i++){
    c = customer_dict[i]
    $('#customer_id').append( '<option value="'  +   c[0]  +   '">'    +    c[2]  + ', ' +  c[1] + '  >  '  +  c[3] +  ' > '  +  c[4]    +  '</option>')
    $('#customer_table').append('<tr><td>' + c[1] + ' ' + c[2] + '</td><td>' + c[3] + '</td><td class="d-none d-md-table-cell">' + c[4] + '</td><td class="table-action"><a class="select-button" id="' + c[0] + '" href="#"><i class="align-middle fas fa-fw fa-arrow-circle-right"></i></a></td></tr>')

    $('.select-button').on('click', function(){
      t = $(this).prop('id')
      $('#confirm_checkbox').prop('checked', false)
      $('#customer_id').prop('value', t)
    })

  }
  $('#mainTable').DataTable()
</script>
{% endblock %}

reuse-data1/qbgiftcard/templates/qbgiftcard/lookup1.html
{% extends 'qbgiftcard/default1.html' %}

{% block title %}Quickbooks Gift Cards - LOOKUP{% endblock %}




{% block header_title %}Quickbooks Gift Cards - LOOKUP{% endblock %}







{% block content %}


<div class="row">
  <div class="col-12 col-sm-4">
    <div class="card" id="print_card">
      <div class="card-header">
        <h5 class="card-title"></h5>
        <h6 class="pt-3 card-subtitle text-muted">Please scan this code in at checkout <br>(Select 'Gift card' as payment type)</h6>
      </div>

      <div class="card-body align-center" id="print_target">
        <h3>{{gift_card_name}}</h3>
        <div  id="datamatrix_target"></div>
        <p>{{access_log.0.DATE_TIME}}</p>
        <button id="print_button" class="btn btn-success">Print</button>
      </div>
    </div>
  </div>

  <div class="col-12 col-sm-8">
    <div class="card">
      <div class="card-header"><h3 class="card-title">ACCESS LOG FOR THIS GIFTCARD</h3></div>
      <div class="card-body align-center">
        <table class="table">
          <thead>
            <tr>
              <th>Date / Time</th>
              <th class="d-none d-md-table-cell" >Staff ID</th>
            </tr>
          </thead>
          <tbody id='giftcard_access_log'>
            {% for i in access_log %}
            <tr><td>{{i.DATE_TIME}}</td><td>{{i.staff_id}}@fingerlakesreuse.org</td></tr>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div

{% endblock %}




{% block javascript_end %}
{% load static %}
<script type="text/javascript" src="{% static 'qbgiftcard/datamatrix.min.js' %}"></script>


<script type="text/javascript">
  // let customer_dict = {{customer_dict | safe}}
$('#datamatrix_target').append(DATAMatrix({'dim':150,'msg':'shopify-giftcard-v1-' + '{{gift_card_code}}' }))

$('#print_button').on('click', function(){
  $('#print_button').remove()
  $('body').html($('#print_target').html())
  $('#print_card').css('background','white')
  print()
})

</script>





{% endblock %}